name: Motorrad mit Herz
favicon: null
layout_spectrum: 0.003543201368302107
typography_spectrum: 0.8927744950633496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.42694979533553123
  lightness: 0.7403194888029248
  saturation: 0.8158887114841491
  rhythmicContrast: 0.9178132801316679
purpose: []
